#include "api_server.h"
#include <winsock2.h>
#include <windows.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
static void reply(SOCKET s,int code,const char*b){char h[256];int n=(int)strlen(b);snprintf(h,sizeof h,"HTTP/1.1 %d OK\r\nContent-Type: application/json\r\nContent-Length: %d\r\nConnection: close\r\n\r\n",code,n);send(s,h,(int)strlen(h),0);send(s,b,n,0);}
static int jstr(const char*b,const char*k,char*o,size_t c){char n[96];snprintf(n,sizeof n,"\"%s\"",k);const char*p=strstr(b,n);if(!p)return 0;p=strchr(p,':');if(!p)return 0;while(*++p==' '||*p=='\t'){}if(*p!='"')return 0;p++;size_t z=0;while(*p&&*p!='"'&&z+1<c){if(*p=='\\'&&p[1])p++;o[z++]=*p++;}o[z]=0;return 1;}
static int jint(const char*b,const char*k,int d){char n[96];snprintf(n,sizeof n,"\"%s\"",k);const char*p=strstr(b,n);if(!p)return d;p=strchr(p,':');return p?atoi(p+1):d;}
static int run(const char*exe,const char*model,const char*prompt,int max,char*out,size_t cap){char cmd[4096];snprintf(cmd,sizeof cmd,"\"%s\" generate \"%s\" \"%s\" --max %d",exe,model,prompt,max);SECURITY_ATTRIBUTES a={sizeof a,0,TRUE};HANDLE r,w;if(!CreatePipe(&r,&w,&a,0))return 0;SetHandleInformation(r,HANDLE_FLAG_INHERIT,0);STARTUPINFOA si={sizeof si};PROCESS_INFORMATION pi={0};si.dwFlags=STARTF_USESTDHANDLES;si.hStdOutput=w;si.hStdError=w;if(!CreateProcessA(0,cmd,0,0,TRUE,CREATE_NO_WINDOW,0,0,&si,&pi)){CloseHandle(r);CloseHandle(w);return 0;}CloseHandle(w);size_t n=0;DWORD got;while(n+1<cap&&ReadFile(r,out+n,(DWORD)(cap-n-1),&got,0)&&got)n+=got;out[n]=0;WaitForSingleObject(pi.hProcess,INFINITE);CloseHandle(pi.hProcess);CloseHandle(pi.hThread);CloseHandle(r);return 1;}
int katali_api_serve(const char*exe,int port){WSADATA w;if(WSAStartup(MAKEWORD(2,2),&w))return 2;SOCKET l=socket(AF_INET,SOCK_STREAM,IPPROTO_TCP);struct sockaddr_in a={0};a.sin_family=AF_INET;a.sin_addr.s_addr=htonl(INADDR_LOOPBACK);a.sin_port=htons((u_short)port);if(l==INVALID_SOCKET||bind(l,(struct sockaddr*)&a,sizeof a)==SOCKET_ERROR||listen(l,4)==SOCKET_ERROR)return 2;printf("API listening on http://127.0.0.1:%d\n",port);for(;;){SOCKET s=accept(l,0,0);if(s==INVALID_SOCKET)break;char q[65536]={0};int n=recv(s,q,sizeof q-1,0);if(n>0){q[n]=0;if(!strncmp(q,"GET /health",11))reply(s,200,"{\"status\":\"ok\",\"cpu_only\":true}");else if(!strncmp(q,"POST /v1/chat/completions",25)||!strncmp(q,"POST /generate",14)){const char*b=strstr(q,"\r\n\r\n");char p[8192]={0},m[1024]={0},o[32768]={0},j[35000];int mx=8;if(b)b+=4;if(b&&!jstr(b,"prompt",p,sizeof p))jstr(b,"content",p,sizeof p);if(b)jstr(b,"model",m,sizeof m);if(!m[0])strcpy(m,"C:\\models\\Qwen_Qwen3.6-35B-A3B-Q4_K_M.gguf");if(b)mx=jint(b,"max_tokens",jint(b,"max",8));if(!p[0])reply(s,400,"{\"error\":\"missing prompt\"}");else if(!run(exe,m,p,mx,o,sizeof o))reply(s,500,"{\"error\":\"generation failed\"}");else{snprintf(j,sizeof j,"{\"id\":\"katali\",\"object\":\"chat.completion\",\"choices\":[{\"index\":0,\"message\":{\"role\":\"assistant\",\"content\":\"%.*s\"},\"finish_reason\":\"stop\"}]}",(int)sizeof(j)-300,o);reply(s,200,j);}}else reply(s,404,"{\"error\":\"not found\"}");}closesocket(s);}closesocket(l);WSACleanup();return 0;}
